world_address = "0x07f87b22d97fcd790a1d784252128540a3f73be8d505558d4de27054da8a4db6"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

